### PR TITLE
Topic fixes and new MD

### PR DESCRIPTION
**Pull request by peteruhnak**
I've fixed some minor errors in Topics.st - syntax errors and missing sections.

Also I've generated the MD file directly from the Topics.st so we can probably automate this step.

### CODE REVIEW

**Comment by SergeStinckwich** [comment]
Great work Peter. How to you automate the generation ?
I start to work on doing it by hand, but better if you do it automatically !

**Comment by Uko** [comment]
I think that we still should aim towards an html page on `gsco.pharo.org` this will look much more professional and we also discussed with Peter possibilities of automatically deploying the page

**Comment by SergeStinckwich** [comment]
ok, you are better than me ;-) Go ahead !

**Comment by peteruhnak** [comment]
I've created an extension for the HTML generator that generates the markdown.

I wrote to Sven as I would like push it back to the project, also I asked him about the automation, so we'll see.

**Comment by SergeStinckwich** [comment]
Ok I merge what you have done until now. Thank you Peter for your help.
I will ask people on the mailing to update the Topics.st file and that we are working on generating the html file from it

**Comment by Uko** [comment]
We will also add a Travis job so we will be (almost) instantly informed if there is any issue in projects format ;)

**Comment by SergeStinckwich** [comment]
Great ! I know why I ask you to join as gsoc 2016 co-admins ;-)

**Comment by peteruhnak** [comment]
> We will also add a Travis job

As I am not member of pharo-project github team, I will need someone who is to sign up on travis-ci.org and enable in Accounts settings building for this project.

**Comment by SergeStinckwich** [comment]
I ask people on pharo-users if someone can add you.

**Pull request merged**
